Participant swap
tianchengc/exable-admin pull request #48
Opened 2024-12-04 03:48 UTC by swapnils118

Fixes: #[Issue Number]

## Description
Tasks done:
- Folder structure of Participant page
- Individual component skeleton created
- Questionnaire Completion component created.

## Feature Link:
- Questionnaire Completion component

## Description:
Added components in participant folder/page and bare skeleton created for each individual component. Questionnaire completion component created which is one of the components of participant page. Added all the styles and classes as per requirement.

---

## Screenshots:
<img width="1440" alt="participantPageComponents" src="https://github.com/user-attachments/assets/2f266e17-c775-405d-8fca-7eb13c6d3893">
<img width="1440" alt="questionnaireCompletionComponent" src="https://github.com/user-attachments/assets/a59fe007-7009-449f-8093-ed31603e969f">

---

## 📢 Notes for Reviewers
Add any additional information or context for the reviewers.

2024-12-04 09:40 UTC, oveed requested changes
Everything else looks good, well done.

2024-12-04 09:40 UTC, oveed commented on src/components/questionnaire-completion.tsx
> +      </footer>
```suggestion
     <footer className=" flex justify-between mt-6 mx-2 w-[370px] text-white underline">
      <small>
          <a >Download</a>
        </small>
        <small>
          <a >View all</a>
        </small>
      </footer>
```

2024-12-04 09:40 UTC, oveed commented on src/pages/participant-profile/index.tsx
> +import QuestionnaireCompletion from '../../components/questionnaire-completion';
I think these should go in the participant profile components

2024-12-04 09:40 UTC, oveed commented on src/pages/participants/style.css
Could you move this to the participant profile style file, participants is another page.

2024-12-05 01:58 UTC, swapnils118 commented on src/pages/participants/style.css
Yes for sure.
You want me to create new route for it?

2024-12-05 02:05 UTC, swapnils118 commented on src/pages/participants/style.css
<img width="1440" alt="Participants" src="https://github.com/user-attachments/assets/82849eac-c64a-46e4-af88-fcde01f519c2">

ATTENTION PLEASE:
Isn't this upcoming block component the same in this design model and the block present in /participants/:id route(which is the block above the one I created?)

2024-12-05 07:49 UTC, oveed approved these changes

2024-12-05 07:50 UTC, oveed commented on src/pages/participants/style.css
Yes i created it, we're working on the same page.

2024-12-05 07:50 UTC, oveed approved these changes

2024-12-05 16:15 UTC, tianchengc commented
@swapnils118 there is merge conflict, could you fix it

2024-12-05 19:28 UTC, merged