Participant swap
tianchengc/exable-admin pull request #53
Opened 2024-12-06 03:17 UTC by swapnils118

Fixes: #38 

## Description
- Added program information block component as per requirement.
- Added components to current /participants/:id route with layout foundation.
- Merge conflicts fixed from current working tree.
- Page title modified to Lung Health Foundation.

## Feature Link:
- Program Information component under participant details page.
- 

## Description:
Participant Information block added to /participant/:id route in sync with existing project structure and layout foundation given to overall page.
Browser's page title is also modified.

---

## Screenshots:
<img width="1440" alt="participant-details" src="https://github.com/user-attachments/assets/9e281f85-2bc6-4618-b098-a33e970c7465">
---

## 📢 Notes for Reviewers
Add any additional information or context for the reviewers.

2024-12-06 10:53 UTC, oveed requested changes
Everything else looks good

2024-12-06 10:53 UTC, oveed commented on src/pages/participant-profile/index.tsx
Well done trying to arrange them but keep the original performance measure component

2024-12-07 01:47 UTC, swapnils118 reviewed
Approved

2024-12-07 03:05 UTC, swapnils118 commented on src/pages/participant-profile/index.tsx
Fixed.
Can you please review it once.
Thanks

2024-12-08 20:26 UTC, oveed approved these changes

2024-12-08 21:24 UTC, HongyuLiuLance commented
I see that you also made changes to the relevant files on the /staff_schedule page. Please upload screenshots or videos of all your implemented and changed parts so far(/staff_schedule page and participants/:id). Also, I don't know what is the purpose of the file src/pages/participants/index.tsx, if it is invalid comment code please remove it.

2024-12-09 00:06 UTC, swapnils118 commented
> I see that you also made changes to the relevant files on the /staff_schedule page. Please upload screenshots or videos of all your implemented and changed parts so far(/staff_schedule page and participants/:id). Also, I don't know what is the purpose of the file src/pages/participants/index.tsx, if it is invalid comment code please remove it.

2024-12-09 00:09 UTC, HongyuLiuLance commented
> I see that you also made changes to the relevant files on the /staff_schedule page. Please upload screenshots or videos of all your implemented and changed parts so far(/staff_schedule page and participants/:id). Also, I don't know what is the purpose of the file src/pages/participants/index.tsx, if it is invalid comment code please remove it.

2024-12-09 00:16 UTC, swapnils118 commented
Hi @HongyuLiuLance, thanks for your review and feedback. I would be more than happy to resolve your concerns:
- I have optimized the code under staff-schedule for create new class modal which was my first contribution for this project and I will be adding ss of the modal and modified code for your reference enclosed within.
- About the other contributions, the respective PR's are already there waiting for approval.
- W.r.t participant/index.tsx, all the unused code is already removed in the latest PR.

Looking forward for any other query :)
<img width="1440" alt="modal" src="https://github.com/user-attachments/assets/4fea8a4a-0571-4e90-887b-be4613e0e2ac">
<img width="1440" alt="staff-schedule" src="https://github.com/user-attachments/assets/b763b18d-f548-461e-87b1-9bd790793868">

2024-12-09 01:10 UTC, tianchengc commented
@swapnils118 could you fix merge conflict, thanks

2024-12-09 21:47 UTC, swapnils118 commented
@tianchengc Yes I am working on it. Will be pushing the final commit soon.

2024-12-10 02:58 UTC, merged